// apps/solid-test/src/routes/index.ts
import {lazy} from 'solid-js'
import type {RouteDefinition} from 'solid-app-router'

export const routes: RouteDefinition[] = [
  {
    children: [
      {component: lazy(() => import('pages/Main')), path: ''},
      {component: lazy(() => import('pages/Sign')), path: 'sign'},
    ],
    component: lazy(() => import('layouts/main-layout/Index')),
    path: '/',
  },
]

// apps/react-test/src/routes/index.tsx
import {lazy} from 'react'
import {RouteObject} from 'react-router-dom'

const MainLayout = lazy(() => import('layouts/main-layout/Index'))
const Main = lazy(() => import('pages/Main'))
const Sign = lazy(() => import('pages/Sign'))

export const routes: RouteObject[] = [
  {
    children: [
      {
        element: <Main />,
        index: true,
      },
      {
        element: <Sign />,
        path: 'sign',
      },
    ],
    element: <MainLayout />,
    path: '/',
  },
]
